name: gmaps_nav_hud_frame
description: "Shows Google Maps turn-by-turn navigation notifications on the Frame (Android only, due to the requirement to read app notifications)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  flutter_notification_listener: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
